// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, PGNFCallibriColorType) {
  PGNFCallibriColorTypeRed = 0,
  PGNFCallibriColorTypeYellow = 1,
  PGNFCallibriColorTypeBlue = 2,
  PGNFCallibriColorTypeWhite = 3,
  PGNFCallibriColorTypeUnknown = 4,
};

/// Wrapper for PGNFCallibriColorType to allow for nullability.
@interface PGNFCallibriColorTypeBox : NSObject
@property(nonatomic, assign) PGNFCallibriColorType value;
- (instancetype)initWithValue:(PGNFCallibriColorType)value;
@end

typedef NS_ENUM(NSUInteger, PGNFCallibriElectrodeState) {
  PGNFCallibriElectrodeStateElStNormal = 0,
  PGNFCallibriElectrodeStateElStHighResistance = 1,
  PGNFCallibriElectrodeStateElStDetached = 2,
};

/// Wrapper for PGNFCallibriElectrodeState to allow for nullability.
@interface PGNFCallibriElectrodeStateBox : NSObject
@property(nonatomic, assign) PGNFCallibriElectrodeState value;
- (instancetype)initWithValue:(PGNFCallibriElectrodeState)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorFilter) {
  PGNFSensorFilterHPFBwhLvl1CutoffFreq1Hz = 0,
  PGNFSensorFilterHPFBwhLvl1CutoffFreq5Hz = 1,
  PGNFSensorFilterBSFBwhLvl2CutoffFreq45_55Hz = 2,
  PGNFSensorFilterBSFBwhLvl2CutoffFreq55_65Hz = 3,
  PGNFSensorFilterHPFBwhLvl2CutoffFreq10Hz = 4,
  PGNFSensorFilterLPFBwhLvl2CutoffFreq400Hz = 5,
  PGNFSensorFilterHPFBwhLvl2CutoffFreq80Hz = 6,
  PGNFSensorFilterUnknown = 7,
};

/// Wrapper for PGNFSensorFilter to allow for nullability.
@interface PGNFSensorFilterBox : NSObject
@property(nonatomic, assign) PGNFSensorFilter value;
- (instancetype)initWithValue:(PGNFSensorFilter)value;
@end

typedef NS_ENUM(NSUInteger, PGNCallibriSignalType) {
  PGNCallibriSignalTypeEEG = 0,
  PGNCallibriSignalTypeEMG = 1,
  PGNCallibriSignalTypeECG = 2,
  PGNCallibriSignalTypeEDA = 3,
  PGNCallibriSignalTypeStrainGaugeBreathing = 4,
  PGNCallibriSignalTypeImpedanceBreathing = 5,
  PGNCallibriSignalTypeTenzoBreathing = 6,
  PGNCallibriSignalTypeUnknown = 7,
};

/// Wrapper for PGNCallibriSignalType to allow for nullability.
@interface PGNCallibriSignalTypeBox : NSObject
@property(nonatomic, assign) PGNCallibriSignalType value;
- (instancetype)initWithValue:(PGNCallibriSignalType)value;
@end

typedef NS_ENUM(NSUInteger, PGNFCallibriStimulatorState) {
  PGNFCallibriStimulatorStateNoParams = 0,
  PGNFCallibriStimulatorStateDisabled = 1,
  PGNFCallibriStimulatorStateEnabled = 2,
  PGNFCallibriStimulatorStateUnsupported = 3,
};

/// Wrapper for PGNFCallibriStimulatorState to allow for nullability.
@interface PGNFCallibriStimulatorStateBox : NSObject
@property(nonatomic, assign) PGNFCallibriStimulatorState value;
- (instancetype)initWithValue:(PGNFCallibriStimulatorState)value;
@end

typedef NS_ENUM(NSUInteger, PGNFCallibriMotionAssistantLimb) {
  PGNFCallibriMotionAssistantLimbRightLeg = 0,
  PGNFCallibriMotionAssistantLimbLeftLeg = 1,
  PGNFCallibriMotionAssistantLimbRightArm = 2,
  PGNFCallibriMotionAssistantLimbLeftArm = 3,
  PGNFCallibriMotionAssistantLimbUnsupported = 4,
};

/// Wrapper for PGNFCallibriMotionAssistantLimb to allow for nullability.
@interface PGNFCallibriMotionAssistantLimbBox : NSObject
@property(nonatomic, assign) PGNFCallibriMotionAssistantLimb value;
- (instancetype)initWithValue:(PGNFCallibriMotionAssistantLimb)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorADCInput) {
  PGNFSensorADCInputElectrodesInp = 0,
  PGNFSensorADCInputShortInp = 1,
  PGNFSensorADCInputTestInp = 2,
  PGNFSensorADCInputResistanceInp = 3,
};

/// Wrapper for PGNFSensorADCInput to allow for nullability.
@interface PGNFSensorADCInputBox : NSObject
@property(nonatomic, assign) PGNFSensorADCInput value;
- (instancetype)initWithValue:(PGNFSensorADCInput)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorCommand) {
  PGNFSensorCommandStartSignal = 0,
  PGNFSensorCommandStopSignal = 1,
  PGNFSensorCommandStartResist = 2,
  PGNFSensorCommandStopResist = 3,
  PGNFSensorCommandStartMEMS = 4,
  PGNFSensorCommandStopMEMS = 5,
  PGNFSensorCommandStartRespiration = 6,
  PGNFSensorCommandStopRespiration = 7,
  PGNFSensorCommandStartCurrentStimulation = 8,
  PGNFSensorCommandStopCurrentStimulation = 9,
  PGNFSensorCommandEnableMotionAssistant = 10,
  PGNFSensorCommandDisableMotionAssistant = 11,
  PGNFSensorCommandFindMe = 12,
  PGNFSensorCommandStartAngle = 13,
  PGNFSensorCommandStopAngle = 14,
  PGNFSensorCommandCalibrateMEMS = 15,
  PGNFSensorCommandResetQuaternion = 16,
  PGNFSensorCommandStartEnvelope = 17,
  PGNFSensorCommandStopEnvelope = 18,
  PGNFSensorCommandResetMotionCounter = 19,
  PGNFSensorCommandCalibrateStimulation = 20,
  PGNFSensorCommandIdle = 21,
  PGNFSensorCommandPowerDown = 22,
  PGNFSensorCommandStartFPG = 23,
  PGNFSensorCommandStopFPG = 24,
  PGNFSensorCommandStartSignalAndResist = 25,
  PGNFSensorCommandStopSignalAndResist = 26,
  PGNFSensorCommandStartPhotoStimulation = 27,
  PGNFSensorCommandStopPhotoStimulation = 28,
  PGNFSensorCommandStartAcousticStimulation = 29,
  PGNFSensorCommandStopAcousticStimulation = 30,
  PGNFSensorCommandFileSystemEnable = 31,
  PGNFSensorCommandFileSystemDisable = 32,
  PGNFSensorCommandFileSystemStreamClose = 33,
  PGNFSensorCommandStartCalibrateSignal = 34,
  PGNFSensorCommandStopCalibrateSignal = 35,
  PGNFSensorCommandPhotoStimEnable = 36,
  PGNFSensorCommandPhotoStimDisable = 37,
};

/// Wrapper for PGNFSensorCommand to allow for nullability.
@interface PGNFSensorCommandBox : NSObject
@property(nonatomic, assign) PGNFSensorCommand value;
- (instancetype)initWithValue:(PGNFSensorCommand)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorDataOffset) {
  PGNFSensorDataOffsetDataOffset0 = 0,
  PGNFSensorDataOffsetDataOffset1 = 1,
  PGNFSensorDataOffsetDataOffset2 = 2,
  PGNFSensorDataOffsetDataOffset3 = 3,
  PGNFSensorDataOffsetDataOffset4 = 4,
  PGNFSensorDataOffsetDataOffset5 = 5,
  PGNFSensorDataOffsetDataOffset6 = 6,
  PGNFSensorDataOffsetDataOffset7 = 7,
  PGNFSensorDataOffsetDataOffset8 = 8,
  PGNFSensorDataOffsetDataOffsetUnsupported = 9,
};

/// Wrapper for PGNFSensorDataOffset to allow for nullability.
@interface PGNFSensorDataOffsetBox : NSObject
@property(nonatomic, assign) PGNFSensorDataOffset value;
- (instancetype)initWithValue:(PGNFSensorDataOffset)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorExternalSwitchInput) {
  PGNFSensorExternalSwitchInputElectrodesRespUSBInp = 0,
  PGNFSensorExternalSwitchInputElectrodesInp = 1,
  PGNFSensorExternalSwitchInputUsbInp = 2,
  PGNFSensorExternalSwitchInputRespUSBInp = 3,
  PGNFSensorExternalSwitchInputShortInp = 4,
  PGNFSensorExternalSwitchInputUnknownInp = 5,
};

/// Wrapper for PGNFSensorExternalSwitchInput to allow for nullability.
@interface PGNFSensorExternalSwitchInputBox : NSObject
@property(nonatomic, assign) PGNFSensorExternalSwitchInput value;
- (instancetype)initWithValue:(PGNFSensorExternalSwitchInput)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorFamily) {
  PGNFSensorFamilyLeCallibri = 0,
  PGNFSensorFamilyLeKolibri = 1,
  PGNFSensorFamilyLeBrainBit = 2,
  PGNFSensorFamilyLeBrainBitBlack = 3,
  PGNFSensorFamilyLeBrainBit2 = 4,
  PGNFSensorFamilyLeBrainBitPro = 5,
  PGNFSensorFamilyLeBrainBitFlex = 6,
  PGNFSensorFamilyUnknown = 7,
};

/// Wrapper for PGNFSensorFamily to allow for nullability.
@interface PGNFSensorFamilyBox : NSObject
@property(nonatomic, assign) PGNFSensorFamily value;
- (instancetype)initWithValue:(PGNFSensorFamily)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorFeature) {
  PGNFSensorFeatureSignal = 0,
  PGNFSensorFeatureMems = 1,
  PGNFSensorFeatureCurrentStimulator = 2,
  PGNFSensorFeatureRespiration = 3,
  PGNFSensorFeatureResist = 4,
  PGNFSensorFeatureFpg = 5,
  PGNFSensorFeatureEnvelope = 6,
  PGNFSensorFeaturePhotoStimulator = 7,
  PGNFSensorFeatureAcousticStimulator = 8,
  PGNFSensorFeatureFlashCard = 9,
  PGNFSensorFeatureLedChannels = 10,
  PGNFSensorFeatureSignalWithResist = 11,
};

/// Wrapper for PGNFSensorFeature to allow for nullability.
@interface PGNFSensorFeatureBox : NSObject
@property(nonatomic, assign) PGNFSensorFeature value;
- (instancetype)initWithValue:(PGNFSensorFeature)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorFirmwareMode) {
  PGNFSensorFirmwareModeModeBootloader = 0,
  PGNFSensorFirmwareModeModeApplication = 1,
};

/// Wrapper for PGNFSensorFirmwareMode to allow for nullability.
@interface PGNFSensorFirmwareModeBox : NSObject
@property(nonatomic, assign) PGNFSensorFirmwareMode value;
- (instancetype)initWithValue:(PGNFSensorFirmwareMode)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorGain) {
  PGNFSensorGainGain1 = 0,
  PGNFSensorGainGain2 = 1,
  PGNFSensorGainGain3 = 2,
  PGNFSensorGainGain4 = 3,
  PGNFSensorGainGain6 = 4,
  PGNFSensorGainGain8 = 5,
  PGNFSensorGainGain12 = 6,
  PGNFSensorGainGain24 = 7,
  PGNFSensorGainGain5 = 8,
  PGNFSensorGainGain2x = 9,
  PGNFSensorGainGain4x = 10,
  PGNFSensorGainGainUnsupported = 11,
};

/// Wrapper for PGNFSensorGain to allow for nullability.
@interface PGNFSensorGainBox : NSObject
@property(nonatomic, assign) PGNFSensorGain value;
- (instancetype)initWithValue:(PGNFSensorGain)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorParameter) {
  PGNFSensorParameterName = 0,
  PGNFSensorParameterState = 1,
  PGNFSensorParameterAddress = 2,
  PGNFSensorParameterSerialNumber = 3,
  PGNFSensorParameterHardwareFilterState = 4,
  PGNFSensorParameterFirmwareMode = 5,
  PGNFSensorParameterSamplingFrequency = 6,
  PGNFSensorParameterGain = 7,
  PGNFSensorParameterOffset = 8,
  PGNFSensorParameterExternalSwitchState = 9,
  PGNFSensorParameterAdcInputState = 10,
  PGNFSensorParameterAccelerometerSens = 11,
  PGNFSensorParameterGyroscopeSens = 12,
  PGNFSensorParameterStimulatorAndMAState = 13,
  PGNFSensorParameterStimulatorParamPack = 14,
  PGNFSensorParameterMotionAssistantParamPack = 15,
  PGNFSensorParameterFirmwareVersion = 16,
  PGNFSensorParameterMemsCalibrationStatus = 17,
  PGNFSensorParameterMotionCounterParamPack = 18,
  PGNFSensorParameterMotionCounter = 19,
  PGNFSensorParameterBattPower = 20,
  PGNFSensorParameterSensorFamily = 21,
  PGNFSensorParameterSensorMode = 22,
  PGNFSensorParameterIrAmplitude = 23,
  PGNFSensorParameterRedAmplitude = 24,
  PGNFSensorParameterEnvelopeAvgWndSz = 25,
  PGNFSensorParameterEnvelopeDecimation = 26,
  PGNFSensorParameterSamplingFrequencyResist = 27,
  PGNFSensorParameterSamplingFrequencyMEMS = 28,
  PGNFSensorParameterSamplingFrequencyFPG = 29,
  PGNFSensorParameterAmplifier = 30,
  PGNFSensorParameterSensorChannels = 31,
  PGNFSensorParameterSamplingFrequencyResp = 32,
  PGNFSensorParameterSurveyId = 33,
  PGNFSensorParameterFileSystemStatus = 34,
  PGNFSensorParameterFileSystemDiskInfo = 35,
  PGNFSensorParameterReferentsShort = 36,
  PGNFSensorParameterReferentsGround = 37,
  PGNFSensorParameterSamplingFrequencyEnvelope = 38,
  PGNFSensorParameterChannelConfiguration = 39,
  PGNFSensorParameterElectrodeState = 40,
  PGNFSensorParameterChannelResistConfiguration = 41,
  PGNFSensorParameterBattVoltage = 42,
  PGNFSensorParameterPhotoStimTimeDefer = 43,
  PGNFSensorParameterPhotoStimSyncState = 44,
  PGNFSensorParameterSensorPhotoStim = 45,
  PGNFSensorParameterStimMode = 46,
  PGNFSensorParameterLedChannels = 47,
  PGNFSensorParameterLedState = 48,
};

/// Wrapper for PGNFSensorParameter to allow for nullability.
@interface PGNFSensorParameterBox : NSObject
@property(nonatomic, assign) PGNFSensorParameter value;
- (instancetype)initWithValue:(PGNFSensorParameter)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorParamAccess) {
  PGNFSensorParamAccessRead = 0,
  PGNFSensorParamAccessReadWrite = 1,
  PGNFSensorParamAccessReadNotify = 2,
};

/// Wrapper for PGNFSensorParamAccess to allow for nullability.
@interface PGNFSensorParamAccessBox : NSObject
@property(nonatomic, assign) PGNFSensorParamAccess value;
- (instancetype)initWithValue:(PGNFSensorParamAccess)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorSamplingFrequency) {
  PGNFSensorSamplingFrequencyHz10 = 0,
  PGNFSensorSamplingFrequencyHz20 = 1,
  PGNFSensorSamplingFrequencyHz100 = 2,
  PGNFSensorSamplingFrequencyHz125 = 3,
  PGNFSensorSamplingFrequencyHz250 = 4,
  PGNFSensorSamplingFrequencyHz500 = 5,
  PGNFSensorSamplingFrequencyHz1000 = 6,
  PGNFSensorSamplingFrequencyHz2000 = 7,
  PGNFSensorSamplingFrequencyHz4000 = 8,
  PGNFSensorSamplingFrequencyHz8000 = 9,
  PGNFSensorSamplingFrequencyHz10000 = 10,
  PGNFSensorSamplingFrequencyHz12000 = 11,
  PGNFSensorSamplingFrequencyHz16000 = 12,
  PGNFSensorSamplingFrequencyHz24000 = 13,
  PGNFSensorSamplingFrequencyHz32000 = 14,
  PGNFSensorSamplingFrequencyHz48000 = 15,
  PGNFSensorSamplingFrequencyHz64000 = 16,
  PGNFSensorSamplingFrequencyUnsupported = 17,
};

/// Wrapper for PGNFSensorSamplingFrequency to allow for nullability.
@interface PGNFSensorSamplingFrequencyBox : NSObject
@property(nonatomic, assign) PGNFSensorSamplingFrequency value;
- (instancetype)initWithValue:(PGNFSensorSamplingFrequency)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorState) {
  PGNFSensorStateInRange = 0,
  PGNFSensorStateOutOfRange = 1,
};

/// Wrapper for PGNFSensorState to allow for nullability.
@interface PGNFSensorStateBox : NSObject
@property(nonatomic, assign) PGNFSensorState value;
- (instancetype)initWithValue:(PGNFSensorState)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorAccelerometerSensitivity) {
  PGNFSensorAccelerometerSensitivityAccSens2g = 0,
  PGNFSensorAccelerometerSensitivityAccSens4g = 1,
  PGNFSensorAccelerometerSensitivityAccSens8g = 2,
  PGNFSensorAccelerometerSensitivityAccSens16g = 3,
  PGNFSensorAccelerometerSensitivityAccSensUnsupported = 4,
};

/// Wrapper for PGNFSensorAccelerometerSensitivity to allow for nullability.
@interface PGNFSensorAccelerometerSensitivityBox : NSObject
@property(nonatomic, assign) PGNFSensorAccelerometerSensitivity value;
- (instancetype)initWithValue:(PGNFSensorAccelerometerSensitivity)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorGyroscopeSensitivity) {
  PGNFSensorGyroscopeSensitivityGyroSens250Grad = 0,
  PGNFSensorGyroscopeSensitivityGyroSens500Grad = 1,
  PGNFSensorGyroscopeSensitivityGyroSens1000Grad = 2,
  PGNFSensorGyroscopeSensitivityGyroSens2000Grad = 3,
  PGNFSensorGyroscopeSensitivityGyroSensUnsupported = 4,
};

/// Wrapper for PGNFSensorGyroscopeSensitivity to allow for nullability.
@interface PGNFSensorGyroscopeSensitivityBox : NSObject
@property(nonatomic, assign) PGNFSensorGyroscopeSensitivity value;
- (instancetype)initWithValue:(PGNFSensorGyroscopeSensitivity)value;
@end

typedef NS_ENUM(NSUInteger, PGNFSensorAmpMode) {
  PGNFSensorAmpModeInvalid = 0,
  PGNFSensorAmpModePowerDown = 1,
  PGNFSensorAmpModeIdle = 2,
  PGNFSensorAmpModeSignal = 3,
  PGNFSensorAmpModeResist = 4,
  PGNFSensorAmpModeSignalResist = 5,
  PGNFSensorAmpModeEnvelope = 6,
};

/// Wrapper for PGNFSensorAmpMode to allow for nullability.
@interface PGNFSensorAmpModeBox : NSObject
@property(nonatomic, assign) PGNFSensorAmpMode value;
- (instancetype)initWithValue:(PGNFSensorAmpMode)value;
@end

typedef NS_ENUM(NSUInteger, PGNFIrAmplitude) {
  PGNFIrAmplitudeIrAmp0 = 0,
  PGNFIrAmplitudeIrAmp14 = 1,
  PGNFIrAmplitudeIrAmp28 = 2,
  PGNFIrAmplitudeIrAmp42 = 3,
  PGNFIrAmplitudeIrAmp56 = 4,
  PGNFIrAmplitudeIrAmp70 = 5,
  PGNFIrAmplitudeIrAmp84 = 6,
  PGNFIrAmplitudeIrAmp100 = 7,
  PGNFIrAmplitudeIrAmpUnsupported = 8,
};

/// Wrapper for PGNFIrAmplitude to allow for nullability.
@interface PGNFIrAmplitudeBox : NSObject
@property(nonatomic, assign) PGNFIrAmplitude value;
- (instancetype)initWithValue:(PGNFIrAmplitude)value;
@end

typedef NS_ENUM(NSUInteger, PGNFRedAmplitude) {
  PGNFRedAmplitudeRedAmp0 = 0,
  PGNFRedAmplitudeRedAmp14 = 1,
  PGNFRedAmplitudeRedAmp28 = 2,
  PGNFRedAmplitudeRedAmp42 = 3,
  PGNFRedAmplitudeRedAmp56 = 4,
  PGNFRedAmplitudeRedAmp70 = 5,
  PGNFRedAmplitudeRedAmp84 = 6,
  PGNFRedAmplitudeRedAmp100 = 7,
  PGNFRedAmplitudeRedAmpUnsupported = 8,
};

/// Wrapper for PGNFRedAmplitude to allow for nullability.
@interface PGNFRedAmplitudeBox : NSObject
@property(nonatomic, assign) PGNFRedAmplitude value;
- (instancetype)initWithValue:(PGNFRedAmplitude)value;
@end

typedef NS_ENUM(NSUInteger, PGNFEEGChannelType) {
  PGNFEEGChannelTypeSingleA1 = 0,
  PGNFEEGChannelTypeSingleA2 = 1,
  PGNFEEGChannelTypeDifferential = 2,
  PGNFEEGChannelTypeRef = 3,
};

/// Wrapper for PGNFEEGChannelType to allow for nullability.
@interface PGNFEEGChannelTypeBox : NSObject
@property(nonatomic, assign) PGNFEEGChannelType value;
- (instancetype)initWithValue:(PGNFEEGChannelType)value;
@end

typedef NS_ENUM(NSUInteger, PGNFEEGChannelId) {
  PGNFEEGChannelIdUnknown = 0,
  PGNFEEGChannelIdO1 = 1,
  PGNFEEGChannelIdP3 = 2,
  PGNFEEGChannelIdC3 = 3,
  PGNFEEGChannelIdF3 = 4,
  PGNFEEGChannelIdFp1 = 5,
  PGNFEEGChannelIdT5 = 6,
  PGNFEEGChannelIdT3 = 7,
  PGNFEEGChannelIdF7 = 8,
  PGNFEEGChannelIdF8 = 9,
  PGNFEEGChannelIdT4 = 10,
  PGNFEEGChannelIdT6 = 11,
  PGNFEEGChannelIdFp2 = 12,
  PGNFEEGChannelIdF4 = 13,
  PGNFEEGChannelIdC4 = 14,
  PGNFEEGChannelIdP4 = 15,
  PGNFEEGChannelIdO2 = 16,
  PGNFEEGChannelIdD1 = 17,
  PGNFEEGChannelIdD2 = 18,
  PGNFEEGChannelIdOZ = 19,
  PGNFEEGChannelIdPZ = 20,
  PGNFEEGChannelIdCZ = 21,
  PGNFEEGChannelIdFZ = 22,
  PGNFEEGChannelIdFpZ = 23,
  PGNFEEGChannelIdD3 = 24,
};

/// Wrapper for PGNFEEGChannelId to allow for nullability.
@interface PGNFEEGChannelIdBox : NSObject
@property(nonatomic, assign) PGNFEEGChannelId value;
- (instancetype)initWithValue:(PGNFEEGChannelId)value;
@end

typedef NS_ENUM(NSUInteger, PGNFBrainBit2ChannelMode) {
  PGNFBrainBit2ChannelModeChModeShort = 0,
  PGNFBrainBit2ChannelModeChModeNormal = 1,
};

/// Wrapper for PGNFBrainBit2ChannelMode to allow for nullability.
@interface PGNFBrainBit2ChannelModeBox : NSObject
@property(nonatomic, assign) PGNFBrainBit2ChannelMode value;
- (instancetype)initWithValue:(PGNFBrainBit2ChannelMode)value;
@end

typedef NS_ENUM(NSUInteger, PGNFGenCurrent) {
  PGNFGenCurrentGenCurr0nA = 0,
  PGNFGenCurrentGenCurr6nA = 1,
  PGNFGenCurrentGenCurr12nA = 2,
  PGNFGenCurrentGenCurr18nA = 3,
  PGNFGenCurrentGenCurr24nA = 4,
  PGNFGenCurrentGenCurr6uA = 5,
  PGNFGenCurrentGenCurr24uA = 6,
  PGNFGenCurrentUnsupported = 7,
};

/// Wrapper for PGNFGenCurrent to allow for nullability.
@interface PGNFGenCurrentBox : NSObject
@property(nonatomic, assign) PGNFGenCurrent value;
- (instancetype)initWithValue:(PGNFGenCurrent)value;
@end

@class PGNFCallibriStimulatorMAState;
@class PGNFCallibriStimulationParams;
@class PGNFCallibriMotionAssistantParams;
@class PGNFCallibriMotionCounterParam;
@class PGNFSensorInfo;
@class PGNFParameterInfo;
@class PGNFSensorVersion;
@class PGNFEEGChannelInfo;
@class PGNBrainBit2AmplifierParamNative;

@interface PGNFCallibriStimulatorMAState : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithStimulatorState:(PGNFCallibriStimulatorState)stimulatorState
    maState:(PGNFCallibriStimulatorState)maState;
@property(nonatomic, assign) PGNFCallibriStimulatorState stimulatorState;
@property(nonatomic, assign) PGNFCallibriStimulatorState maState;
@end

@interface PGNFCallibriStimulationParams : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCurrent:(NSInteger )current
    pulseWidth:(NSInteger )pulseWidth
    frequency:(NSInteger )frequency
    stimulusDuration:(NSInteger )stimulusDuration;
@property(nonatomic, assign) NSInteger  current;
@property(nonatomic, assign) NSInteger  pulseWidth;
@property(nonatomic, assign) NSInteger  frequency;
@property(nonatomic, assign) NSInteger  stimulusDuration;
@end

@interface PGNFCallibriMotionAssistantParams : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithGyroStart:(NSInteger )gyroStart
    gyroStop:(NSInteger )gyroStop
    limb:(PGNFCallibriMotionAssistantLimb)limb
    minPauseMs:(NSInteger )minPauseMs;
@property(nonatomic, assign) NSInteger  gyroStart;
@property(nonatomic, assign) NSInteger  gyroStop;
@property(nonatomic, assign) PGNFCallibriMotionAssistantLimb limb;
@property(nonatomic, assign) NSInteger  minPauseMs;
@end

@interface PGNFCallibriMotionCounterParam : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithInsenseThresholdMG:(NSInteger )insenseThresholdMG
    insenseThresholdSample:(NSInteger )insenseThresholdSample;
@property(nonatomic, assign) NSInteger  insenseThresholdMG;
@property(nonatomic, assign) NSInteger  insenseThresholdSample;
@end

@interface PGNFSensorInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithName:(NSString *)name
    address:(NSString *)address
    serialNumber:(NSString *)serialNumber
    pairingRequired:(BOOL )pairingRequired
    sensModel:(NSInteger )sensModel
    sensFamily:(PGNFSensorFamily)sensFamily
    rssi:(NSInteger )rssi;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, copy) NSString * address;
@property(nonatomic, copy) NSString * serialNumber;
@property(nonatomic, assign) BOOL  pairingRequired;
@property(nonatomic, assign) NSInteger  sensModel;
@property(nonatomic, assign) PGNFSensorFamily sensFamily;
@property(nonatomic, assign) NSInteger  rssi;
@end

@interface PGNFParameterInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithParam:(PGNFSensorParameter)param
    paramAccess:(PGNFSensorParamAccess)paramAccess;
@property(nonatomic, assign) PGNFSensorParameter param;
@property(nonatomic, assign) PGNFSensorParamAccess paramAccess;
@end

@interface PGNFSensorVersion : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithFwMajor:(NSInteger )fwMajor
    fwMinor:(NSInteger )fwMinor
    fwPatch:(NSInteger )fwPatch
    hwMajor:(NSInteger )hwMajor
    hwMinor:(NSInteger )hwMinor
    hwPatch:(NSInteger )hwPatch
    extMajor:(NSInteger )extMajor;
@property(nonatomic, assign) NSInteger  fwMajor;
@property(nonatomic, assign) NSInteger  fwMinor;
@property(nonatomic, assign) NSInteger  fwPatch;
@property(nonatomic, assign) NSInteger  hwMajor;
@property(nonatomic, assign) NSInteger  hwMinor;
@property(nonatomic, assign) NSInteger  hwPatch;
@property(nonatomic, assign) NSInteger  extMajor;
@end

@interface PGNFEEGChannelInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(PGNFEEGChannelId)id
    chType:(PGNFEEGChannelType)chType
    name:(NSString *)name
    num:(NSInteger )num;
@property(nonatomic, assign) PGNFEEGChannelId id;
@property(nonatomic, assign) PGNFEEGChannelType chType;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, assign) NSInteger  num;
@end

@interface PGNBrainBit2AmplifierParamNative : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithChSignalMode:(NSArray<NSNumber *> *)chSignalMode
    chResistUse:(NSArray<NSNumber *> *)chResistUse
    chGain:(NSArray<NSNumber *> *)chGain
    current:(PGNFGenCurrent)current;
@property(nonatomic, copy) NSArray<NSNumber *> * chSignalMode;
@property(nonatomic, copy) NSArray<NSNumber *> * chResistUse;
@property(nonatomic, copy) NSArray<NSNumber *> * chGain;
@property(nonatomic, assign) PGNFGenCurrent current;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *PGNGetPigeonMessagesCodec(void);

@protocol PGNNeuroApi
- (void)createScannerFilters:(NSArray<NSNumber *> *)filters completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)closeScannerGuid:(NSString *)guid completion:(void (^)(FlutterError *_Nullable))completion;
- (void)startScanGuid:(NSString *)guid completion:(void (^)(FlutterError *_Nullable))completion;
- (void)stopScanGuid:(NSString *)guid completion:(void (^)(FlutterError *_Nullable))completion;
- (void)createSensorGuid:(NSString *)guid sensorInfo:(PGNFSensorInfo *)sensorInfo completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<PGNFSensorInfo *> *)getSensorsGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)closeSensorGuid:(NSString *)guid completion:(void (^)(FlutterError *_Nullable))completion;
- (void)connectSensorGuid:(NSString *)guid completion:(void (^)(FlutterError *_Nullable))completion;
- (void)disconnectSensorGuid:(NSString *)guid completion:(void (^)(FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<NSNumber *> *)supportedFeaturesGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isSupportedFeatureGuid:(NSString *)guid feature:(PGNFSensorFeature)feature error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<NSNumber *> *)supportedCommandsGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isSupportedCommandGuid:(NSString *)guid command:(PGNFSensorCommand)command error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<PGNFParameterInfo *> *)supportedParametersGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isSupportedParameterGuid:(NSString *)guid parameter:(PGNFSensorParameter)parameter error:(FlutterError *_Nullable *_Nonnull)error;
- (void)execCommandGuid:(NSString *)guid command:(PGNFSensorCommand)command completion:(void (^)(FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getNameGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setNameGuid:(NSString *)guid name:(NSString *)name error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorStateBox *_Nullable)getStateGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getAddressGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getSerialNumberGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setSerialNumberGuid:(NSString *)guid sn:(NSString *)sn error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getBattPowerGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorSamplingFrequencyBox *_Nullable)getSamplingFrequencyGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorGainBox *_Nullable)getGainGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorDataOffsetBox *_Nullable)getDataOffsetGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorFirmwareModeBox *_Nullable)getFirmwareModeGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable PGNFSensorVersion *)getVersionGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getChannelsCountGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorFamilyBox *_Nullable)getSensFamilyGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorAmpModeBox *_Nullable)getAmpModeGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorSamplingFrequencyBox *_Nullable)getSamplingFrequencyResistGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorSamplingFrequencyBox *_Nullable)getSamplingFrequencyFPGGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFIrAmplitudeBox *_Nullable)getIrAmplitudeGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setIrAmplitudeGuid:(NSString *)guid amp:(PGNFIrAmplitude)amp error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFRedAmplitudeBox *_Nullable)getRedAmplitudeGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setRedAmplitudeGuid:(NSString *)guid amp:(PGNFRedAmplitude)amp error:(FlutterError *_Nullable *_Nonnull)error;
- (void)pingNeuroSmartGuid:(NSString *)guid marker:(NSInteger)marker completion:(void (^)(FlutterError *_Nullable))completion;
- (void)setGainGuid:(NSString *)guid gain:(PGNFSensorGain)gain error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isSupportedFilterGuid:(NSString *)guid filter:(PGNFSensorFilter)filter error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<NSNumber *> *)getSupportedFiltersGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<NSNumber *> *)getHardwareFiltersGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setHardwareFiltersGuid:(NSString *)guid filters:(NSArray<NSNumber *> *)filters error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setFirmwareModeGuid:(NSString *)guid mode:(PGNFSensorFirmwareMode)mode error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setSamplingFrequencyGuid:(NSString *)guid sf:(PGNFSensorSamplingFrequency)sf error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setDataOffsetGuid:(NSString *)guid offset:(PGNFSensorDataOffset)offset error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorExternalSwitchInputBox *_Nullable)getExtSwInputGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setExtSwInputGuid:(NSString *)guid extSwInp:(PGNFSensorExternalSwitchInput)extSwInp error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorADCInputBox *_Nullable)getADCInputGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setADCInputGuid:(NSString *)guid adcInp:(PGNFSensorADCInput)adcInp error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable PGNFCallibriStimulatorMAState *)getStimulatorMAStateGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable PGNFCallibriStimulationParams *)getStimulatorParamGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setStimulatorParamGuid:(NSString *)guid param:(PGNFCallibriStimulationParams *)param error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable PGNFCallibriMotionAssistantParams *)getMotionAssistantParamGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setMotionAssistantParamGuid:(NSString *)guid param:(PGNFCallibriMotionAssistantParams *)param error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable PGNFCallibriMotionCounterParam *)getMotionCounterParamGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setMotionCounterParamGuid:(NSString *)guid param:(PGNFCallibriMotionCounterParam *)param error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getMotionCounterGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFCallibriColorTypeBox *_Nullable)getColorGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getMEMSCalibrateStateGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorSamplingFrequencyBox *_Nullable)getSamplingFrequencyRespGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorSamplingFrequencyBox *_Nullable)getSamplingFrequencyEnvelopeGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNCallibriSignalTypeBox *_Nullable)getSignalTypeGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setSignalTypeGuid:(NSString *)guid type:(PGNCallibriSignalType)type error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFCallibriElectrodeStateBox *_Nullable)getElectrodeStateGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorAccelerometerSensitivityBox *_Nullable)getAccSensGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setAccSensGuid:(NSString *)guid accSens:(PGNFSensorAccelerometerSensitivity)accSens error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorGyroscopeSensitivityBox *_Nullable)getGyroSensGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setGyroSensGuid:(NSString *)guid gyroSens:(PGNFSensorGyroscopeSensitivity)gyroSens error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (PGNFSensorSamplingFrequencyBox *_Nullable)getSamplingFrequencyMEMSGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<PGNFEEGChannelInfo *> *)getSupportedChannelsGuid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable PGNBrainBit2AmplifierParamNative *)getAmplifierParamBB2Guid:(NSString *)guid error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setAmplifierParamBB2Guid:(NSString *)guid param:(PGNBrainBit2AmplifierParamNative *)param error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpPGNNeuroApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNNeuroApi> *_Nullable api);

extern void SetUpPGNNeuroApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNNeuroApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
