// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_PIGEON_MESSAGES_G_H_
#define PIGEON_PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace pigeon_neuro_api {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class NeuroApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class FCallibriColorType {
  kRed = 0,
  kYellow = 1,
  kBlue = 2,
  kWhite = 3,
  kUnknown = 4
};

enum class FCallibriElectrodeState {
  kElStNormal = 0,
  kElStHighResistance = 1,
  kElStDetached = 2
};

enum class FSensorFilter {
  kHPFBwhLvl1CutoffFreq1Hz = 0,
  kHPFBwhLvl1CutoffFreq5Hz = 1,
  kBSFBwhLvl2CutoffFreq45_55Hz = 2,
  kBSFBwhLvl2CutoffFreq55_65Hz = 3,
  kHPFBwhLvl2CutoffFreq10Hz = 4,
  kLPFBwhLvl2CutoffFreq400Hz = 5,
  kHPFBwhLvl2CutoffFreq80Hz = 6,
  kUnknown = 7
};

enum class CallibriSignalType {
  kEEG = 0,
  kEMG = 1,
  kECG = 2,
  kEDA = 3,
  kStrainGaugeBreathing = 4,
  kImpedanceBreathing = 5,
  kTenzoBreathing = 6,
  kUnknown = 7
};

enum class FCallibriStimulatorState {
  kNoParams = 0,
  kDisabled = 1,
  kEnabled = 2,
  kUnsupported = 3
};

enum class FCallibriMotionAssistantLimb {
  kRightLeg = 0,
  kLeftLeg = 1,
  kRightArm = 2,
  kLeftArm = 3,
  kUnsupported = 4
};

enum class FSensorADCInput {
  kElectrodesInp = 0,
  kShortInp = 1,
  kTestInp = 2,
  kResistanceInp = 3
};

enum class FSensorCommand {
  kStartSignal = 0,
  kStopSignal = 1,
  kStartResist = 2,
  kStopResist = 3,
  kStartMEMS = 4,
  kStopMEMS = 5,
  kStartRespiration = 6,
  kStopRespiration = 7,
  kStartCurrentStimulation = 8,
  kStopCurrentStimulation = 9,
  kEnableMotionAssistant = 10,
  kDisableMotionAssistant = 11,
  kFindMe = 12,
  kStartAngle = 13,
  kStopAngle = 14,
  kCalibrateMEMS = 15,
  kResetQuaternion = 16,
  kStartEnvelope = 17,
  kStopEnvelope = 18,
  kResetMotionCounter = 19,
  kCalibrateStimulation = 20,
  kIdle = 21,
  kPowerDown = 22,
  kStartFPG = 23,
  kStopFPG = 24,
  kStartSignalAndResist = 25,
  kStopSignalAndResist = 26,
  kStartPhotoStimulation = 27,
  kStopPhotoStimulation = 28,
  kStartAcousticStimulation = 29,
  kStopAcousticStimulation = 30,
  kFileSystemEnable = 31,
  kFileSystemDisable = 32,
  kFileSystemStreamClose = 33,
  kStartCalibrateSignal = 34,
  kStopCalibrateSignal = 35,
  kPhotoStimEnable = 36,
  kPhotoStimDisable = 37
};

enum class FSensorDataOffset {
  kDataOffset0 = 0,
  kDataOffset1 = 1,
  kDataOffset2 = 2,
  kDataOffset3 = 3,
  kDataOffset4 = 4,
  kDataOffset5 = 5,
  kDataOffset6 = 6,
  kDataOffset7 = 7,
  kDataOffset8 = 8,
  kDataOffsetUnsupported = 9
};

enum class FSensorExternalSwitchInput {
  kElectrodesRespUSBInp = 0,
  kElectrodesInp = 1,
  kUsbInp = 2,
  kRespUSBInp = 3,
  kShortInp = 4,
  kUnknownInp = 5
};

enum class FSensorFamily {
  kLeCallibri = 0,
  kLeKolibri = 1,
  kLeBrainBit = 2,
  kLeBrainBitBlack = 3,
  kLeBrainBit2 = 4,
  kLeBrainBitPro = 5,
  kLeBrainBitFlex = 6,
  kUnknown = 7
};

enum class FSensorFeature {
  kSignal = 0,
  kMems = 1,
  kCurrentStimulator = 2,
  kRespiration = 3,
  kResist = 4,
  kFpg = 5,
  kEnvelope = 6,
  kPhotoStimulator = 7,
  kAcousticStimulator = 8,
  kFlashCard = 9,
  kLedChannels = 10,
  kSignalWithResist = 11
};

enum class FSensorFirmwareMode {
  kModeBootloader = 0,
  kModeApplication = 1
};

enum class FSensorGain {
  kGain1 = 0,
  kGain2 = 1,
  kGain3 = 2,
  kGain4 = 3,
  kGain6 = 4,
  kGain8 = 5,
  kGain12 = 6,
  kGain24 = 7,
  kGain5 = 8,
  kGain2x = 9,
  kGain4x = 10,
  kGainUnsupported = 11
};

enum class FSensorParameter {
  kName = 0,
  kState = 1,
  kAddress = 2,
  kSerialNumber = 3,
  kHardwareFilterState = 4,
  kFirmwareMode = 5,
  kSamplingFrequency = 6,
  kGain = 7,
  kOffset = 8,
  kExternalSwitchState = 9,
  kAdcInputState = 10,
  kAccelerometerSens = 11,
  kGyroscopeSens = 12,
  kStimulatorAndMAState = 13,
  kStimulatorParamPack = 14,
  kMotionAssistantParamPack = 15,
  kFirmwareVersion = 16,
  kMemsCalibrationStatus = 17,
  kMotionCounterParamPack = 18,
  kMotionCounter = 19,
  kBattPower = 20,
  kSensorFamily = 21,
  kSensorMode = 22,
  kIrAmplitude = 23,
  kRedAmplitude = 24,
  kEnvelopeAvgWndSz = 25,
  kEnvelopeDecimation = 26,
  kSamplingFrequencyResist = 27,
  kSamplingFrequencyMEMS = 28,
  kSamplingFrequencyFPG = 29,
  kAmplifier = 30,
  kSensorChannels = 31,
  kSamplingFrequencyResp = 32,
  kSurveyId = 33,
  kFileSystemStatus = 34,
  kFileSystemDiskInfo = 35,
  kReferentsShort = 36,
  kReferentsGround = 37,
  kSamplingFrequencyEnvelope = 38,
  kChannelConfiguration = 39,
  kElectrodeState = 40,
  kChannelResistConfiguration = 41,
  kBattVoltage = 42,
  kPhotoStimTimeDefer = 43,
  kPhotoStimSyncState = 44,
  kSensorPhotoStim = 45,
  kStimMode = 46,
  kLedChannels = 47,
  kLedState = 48
};

enum class FSensorParamAccess {
  kRead = 0,
  kReadWrite = 1,
  kReadNotify = 2
};

enum class FSensorSamplingFrequency {
  kHz10 = 0,
  kHz20 = 1,
  kHz100 = 2,
  kHz125 = 3,
  kHz250 = 4,
  kHz500 = 5,
  kHz1000 = 6,
  kHz2000 = 7,
  kHz4000 = 8,
  kHz8000 = 9,
  kHz10000 = 10,
  kHz12000 = 11,
  kHz16000 = 12,
  kHz24000 = 13,
  kHz32000 = 14,
  kHz48000 = 15,
  kHz64000 = 16,
  kUnsupported = 17
};

enum class FSensorState {
  kInRange = 0,
  kOutOfRange = 1
};

enum class FSensorAccelerometerSensitivity {
  kAccSens2g = 0,
  kAccSens4g = 1,
  kAccSens8g = 2,
  kAccSens16g = 3,
  kAccSensUnsupported = 4
};

enum class FSensorGyroscopeSensitivity {
  kGyroSens250Grad = 0,
  kGyroSens500Grad = 1,
  kGyroSens1000Grad = 2,
  kGyroSens2000Grad = 3,
  kGyroSensUnsupported = 4
};

enum class FSensorAmpMode {
  kInvalid = 0,
  kPowerDown = 1,
  kIdle = 2,
  kSignal = 3,
  kResist = 4,
  kSignalResist = 5,
  kEnvelope = 6
};

enum class FIrAmplitude {
  kIrAmp0 = 0,
  kIrAmp14 = 1,
  kIrAmp28 = 2,
  kIrAmp42 = 3,
  kIrAmp56 = 4,
  kIrAmp70 = 5,
  kIrAmp84 = 6,
  kIrAmp100 = 7,
  kIrAmpUnsupported = 8
};

enum class FRedAmplitude {
  kRedAmp0 = 0,
  kRedAmp14 = 1,
  kRedAmp28 = 2,
  kRedAmp42 = 3,
  kRedAmp56 = 4,
  kRedAmp70 = 5,
  kRedAmp84 = 6,
  kRedAmp100 = 7,
  kRedAmpUnsupported = 8
};

enum class FEEGChannelType {
  kSingleA1 = 0,
  kSingleA2 = 1,
  kDifferential = 2,
  kRef = 3
};

enum class FEEGChannelId {
  kUnknown = 0,
  kO1 = 1,
  kP3 = 2,
  kC3 = 3,
  kF3 = 4,
  kFp1 = 5,
  kT5 = 6,
  kT3 = 7,
  kF7 = 8,
  kF8 = 9,
  kT4 = 10,
  kT6 = 11,
  kFp2 = 12,
  kF4 = 13,
  kC4 = 14,
  kP4 = 15,
  kO2 = 16,
  kD1 = 17,
  kD2 = 18,
  kOZ = 19,
  kPZ = 20,
  kCZ = 21,
  kFZ = 22,
  kFpZ = 23,
  kD3 = 24
};

enum class FBrainBit2ChannelMode {
  kChModeShort = 0,
  kChModeNormal = 1
};

enum class FGenCurrent {
  kGenCurr0nA = 0,
  kGenCurr6nA = 1,
  kGenCurr12nA = 2,
  kGenCurr18nA = 3,
  kGenCurr24nA = 4,
  kGenCurr6uA = 5,
  kGenCurr24uA = 6,
  kUnsupported = 7
};


// Generated class from Pigeon that represents data sent in messages.
class FCallibriStimulatorMAState {
 public:
  // Constructs an object setting all fields.
  explicit FCallibriStimulatorMAState(
    const FCallibriStimulatorState& stimulator_state,
    const FCallibriStimulatorState& ma_state);

  const FCallibriStimulatorState& stimulator_state() const;
  void set_stimulator_state(const FCallibriStimulatorState& value_arg);

  const FCallibriStimulatorState& ma_state() const;
  void set_ma_state(const FCallibriStimulatorState& value_arg);

 private:
  static FCallibriStimulatorMAState FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class NeuroApi;
  friend class PigeonInternalCodecSerializer;
  FCallibriStimulatorState stimulator_state_;
  FCallibriStimulatorState ma_state_;
};


// Generated class from Pigeon that represents data sent in messages.
class FCallibriStimulationParams {
 public:
  // Constructs an object setting all fields.
  explicit FCallibriStimulationParams(
    int64_t current,
    int64_t pulse_width,
    int64_t frequency,
    int64_t stimulus_duration);

  int64_t current() const;
  void set_current(int64_t value_arg);

  int64_t pulse_width() const;
  void set_pulse_width(int64_t value_arg);

  int64_t frequency() const;
  void set_frequency(int64_t value_arg);

  int64_t stimulus_duration() const;
  void set_stimulus_duration(int64_t value_arg);

 private:
  static FCallibriStimulationParams FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class NeuroApi;
  friend class PigeonInternalCodecSerializer;
  int64_t current_;
  int64_t pulse_width_;
  int64_t frequency_;
  int64_t stimulus_duration_;
};


// Generated class from Pigeon that represents data sent in messages.
class FCallibriMotionAssistantParams {
 public:
  // Constructs an object setting all fields.
  explicit FCallibriMotionAssistantParams(
    int64_t gyro_start,
    int64_t gyro_stop,
    const FCallibriMotionAssistantLimb& limb,
    int64_t min_pause_ms);

  int64_t gyro_start() const;
  void set_gyro_start(int64_t value_arg);

  int64_t gyro_stop() const;
  void set_gyro_stop(int64_t value_arg);

  const FCallibriMotionAssistantLimb& limb() const;
  void set_limb(const FCallibriMotionAssistantLimb& value_arg);

  int64_t min_pause_ms() const;
  void set_min_pause_ms(int64_t value_arg);

 private:
  static FCallibriMotionAssistantParams FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class NeuroApi;
  friend class PigeonInternalCodecSerializer;
  int64_t gyro_start_;
  int64_t gyro_stop_;
  FCallibriMotionAssistantLimb limb_;
  int64_t min_pause_ms_;
};


// Generated class from Pigeon that represents data sent in messages.
class FCallibriMotionCounterParam {
 public:
  // Constructs an object setting all fields.
  explicit FCallibriMotionCounterParam(
    int64_t insense_threshold_m_g,
    int64_t insense_threshold_sample);

  int64_t insense_threshold_m_g() const;
  void set_insense_threshold_m_g(int64_t value_arg);

  int64_t insense_threshold_sample() const;
  void set_insense_threshold_sample(int64_t value_arg);

 private:
  static FCallibriMotionCounterParam FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class NeuroApi;
  friend class PigeonInternalCodecSerializer;
  int64_t insense_threshold_m_g_;
  int64_t insense_threshold_sample_;
};


// Generated class from Pigeon that represents data sent in messages.
class FSensorInfo {
 public:
  // Constructs an object setting all fields.
  explicit FSensorInfo(
    const std::string& name,
    const std::string& address,
    const std::string& serial_number,
    bool pairing_required,
    int64_t sens_model,
    const FSensorFamily& sens_family,
    int64_t rssi);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  const std::string& address() const;
  void set_address(std::string_view value_arg);

  const std::string& serial_number() const;
  void set_serial_number(std::string_view value_arg);

  bool pairing_required() const;
  void set_pairing_required(bool value_arg);

  int64_t sens_model() const;
  void set_sens_model(int64_t value_arg);

  const FSensorFamily& sens_family() const;
  void set_sens_family(const FSensorFamily& value_arg);

  int64_t rssi() const;
  void set_rssi(int64_t value_arg);

 private:
  static FSensorInfo FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class NeuroApi;
  friend class PigeonInternalCodecSerializer;
  std::string name_;
  std::string address_;
  std::string serial_number_;
  bool pairing_required_;
  int64_t sens_model_;
  FSensorFamily sens_family_;
  int64_t rssi_;
};


// Generated class from Pigeon that represents data sent in messages.
class FParameterInfo {
 public:
  // Constructs an object setting all fields.
  explicit FParameterInfo(
    const FSensorParameter& param,
    const FSensorParamAccess& param_access);

  const FSensorParameter& param() const;
  void set_param(const FSensorParameter& value_arg);

  const FSensorParamAccess& param_access() const;
  void set_param_access(const FSensorParamAccess& value_arg);

 private:
  static FParameterInfo FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class NeuroApi;
  friend class PigeonInternalCodecSerializer;
  FSensorParameter param_;
  FSensorParamAccess param_access_;
};


// Generated class from Pigeon that represents data sent in messages.
class FSensorVersion {
 public:
  // Constructs an object setting all fields.
  explicit FSensorVersion(
    int64_t fw_major,
    int64_t fw_minor,
    int64_t fw_patch,
    int64_t hw_major,
    int64_t hw_minor,
    int64_t hw_patch,
    int64_t ext_major);

  int64_t fw_major() const;
  void set_fw_major(int64_t value_arg);

  int64_t fw_minor() const;
  void set_fw_minor(int64_t value_arg);

  int64_t fw_patch() const;
  void set_fw_patch(int64_t value_arg);

  int64_t hw_major() const;
  void set_hw_major(int64_t value_arg);

  int64_t hw_minor() const;
  void set_hw_minor(int64_t value_arg);

  int64_t hw_patch() const;
  void set_hw_patch(int64_t value_arg);

  int64_t ext_major() const;
  void set_ext_major(int64_t value_arg);

 private:
  static FSensorVersion FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class NeuroApi;
  friend class PigeonInternalCodecSerializer;
  int64_t fw_major_;
  int64_t fw_minor_;
  int64_t fw_patch_;
  int64_t hw_major_;
  int64_t hw_minor_;
  int64_t hw_patch_;
  int64_t ext_major_;
};


// Generated class from Pigeon that represents data sent in messages.
class FEEGChannelInfo {
 public:
  // Constructs an object setting all fields.
  explicit FEEGChannelInfo(
    const FEEGChannelId& id,
    const FEEGChannelType& ch_type,
    const std::string& name,
    int64_t num);

  const FEEGChannelId& id() const;
  void set_id(const FEEGChannelId& value_arg);

  const FEEGChannelType& ch_type() const;
  void set_ch_type(const FEEGChannelType& value_arg);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  int64_t num() const;
  void set_num(int64_t value_arg);

 private:
  static FEEGChannelInfo FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class NeuroApi;
  friend class PigeonInternalCodecSerializer;
  FEEGChannelId id_;
  FEEGChannelType ch_type_;
  std::string name_;
  int64_t num_;
};


// Generated class from Pigeon that represents data sent in messages.
class BrainBit2AmplifierParamNative {
 public:
  // Constructs an object setting all fields.
  explicit BrainBit2AmplifierParamNative(
    const flutter::EncodableList& ch_signal_mode,
    const flutter::EncodableList& ch_resist_use,
    const flutter::EncodableList& ch_gain,
    const FGenCurrent& current);

  const flutter::EncodableList& ch_signal_mode() const;
  void set_ch_signal_mode(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& ch_resist_use() const;
  void set_ch_resist_use(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& ch_gain() const;
  void set_ch_gain(const flutter::EncodableList& value_arg);

  const FGenCurrent& current() const;
  void set_current(const FGenCurrent& value_arg);

 private:
  static BrainBit2AmplifierParamNative FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class NeuroApi;
  friend class PigeonInternalCodecSerializer;
  flutter::EncodableList ch_signal_mode_;
  flutter::EncodableList ch_resist_use_;
  flutter::EncodableList ch_gain_;
  FGenCurrent current_;
};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;
 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class NeuroApi {
 public:
  NeuroApi(const NeuroApi&) = delete;
  NeuroApi& operator=(const NeuroApi&) = delete;
  virtual ~NeuroApi() {}
  virtual void CreateScanner(
    const flutter::EncodableList& filters,
    std::function<void(ErrorOr<std::string> reply)> result) = 0;
  virtual void CloseScanner(
    const std::string& guid,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void StartScan(
    const std::string& guid,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void StopScan(
    const std::string& guid,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void CreateSensor(
    const std::string& guid,
    const FSensorInfo& sensor_info,
    std::function<void(ErrorOr<std::string> reply)> result) = 0;
  virtual ErrorOr<flutter::EncodableList> GetSensors(const std::string& guid) = 0;
  virtual void CloseSensor(
    const std::string& guid,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void ConnectSensor(
    const std::string& guid,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void DisconnectSensor(
    const std::string& guid,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual ErrorOr<flutter::EncodableList> SupportedFeatures(const std::string& guid) = 0;
  virtual ErrorOr<bool> IsSupportedFeature(
    const std::string& guid,
    const FSensorFeature& feature) = 0;
  virtual ErrorOr<flutter::EncodableList> SupportedCommands(const std::string& guid) = 0;
  virtual ErrorOr<bool> IsSupportedCommand(
    const std::string& guid,
    const FSensorCommand& command) = 0;
  virtual ErrorOr<flutter::EncodableList> SupportedParameters(const std::string& guid) = 0;
  virtual ErrorOr<bool> IsSupportedParameter(
    const std::string& guid,
    const FSensorParameter& parameter) = 0;
  virtual void ExecCommand(
    const std::string& guid,
    const FSensorCommand& command,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual ErrorOr<std::string> GetName(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetName(
    const std::string& guid,
    const std::string& name) = 0;
  virtual ErrorOr<FSensorState> GetState(const std::string& guid) = 0;
  virtual ErrorOr<std::string> GetAddress(const std::string& guid) = 0;
  virtual ErrorOr<std::string> GetSerialNumber(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetSerialNumber(
    const std::string& guid,
    const std::string& sn) = 0;
  virtual ErrorOr<int64_t> GetBattPower(const std::string& guid) = 0;
  virtual ErrorOr<FSensorSamplingFrequency> GetSamplingFrequency(const std::string& guid) = 0;
  virtual ErrorOr<FSensorGain> GetGain(const std::string& guid) = 0;
  virtual ErrorOr<FSensorDataOffset> GetDataOffset(const std::string& guid) = 0;
  virtual ErrorOr<FSensorFirmwareMode> GetFirmwareMode(const std::string& guid) = 0;
  virtual ErrorOr<FSensorVersion> GetVersion(const std::string& guid) = 0;
  virtual ErrorOr<int64_t> GetChannelsCount(const std::string& guid) = 0;
  virtual ErrorOr<FSensorFamily> GetSensFamily(const std::string& guid) = 0;
  virtual ErrorOr<FSensorAmpMode> GetAmpMode(const std::string& guid) = 0;
  virtual ErrorOr<FSensorSamplingFrequency> GetSamplingFrequencyResist(const std::string& guid) = 0;
  virtual ErrorOr<FSensorSamplingFrequency> GetSamplingFrequencyFPG(const std::string& guid) = 0;
  virtual ErrorOr<FIrAmplitude> GetIrAmplitude(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetIrAmplitude(
    const std::string& guid,
    const FIrAmplitude& amp) = 0;
  virtual ErrorOr<FRedAmplitude> GetRedAmplitude(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetRedAmplitude(
    const std::string& guid,
    const FRedAmplitude& amp) = 0;
  virtual void PingNeuroSmart(
    const std::string& guid,
    int64_t marker,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual std::optional<FlutterError> SetGain(
    const std::string& guid,
    const FSensorGain& gain) = 0;
  virtual ErrorOr<bool> IsSupportedFilter(
    const std::string& guid,
    const FSensorFilter& filter) = 0;
  virtual ErrorOr<flutter::EncodableList> GetSupportedFilters(const std::string& guid) = 0;
  virtual ErrorOr<flutter::EncodableList> GetHardwareFilters(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetHardwareFilters(
    const std::string& guid,
    const flutter::EncodableList& filters) = 0;
  virtual std::optional<FlutterError> SetFirmwareMode(
    const std::string& guid,
    const FSensorFirmwareMode& mode) = 0;
  virtual std::optional<FlutterError> SetSamplingFrequency(
    const std::string& guid,
    const FSensorSamplingFrequency& sf) = 0;
  virtual std::optional<FlutterError> SetDataOffset(
    const std::string& guid,
    const FSensorDataOffset& offset) = 0;
  virtual ErrorOr<FSensorExternalSwitchInput> GetExtSwInput(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetExtSwInput(
    const std::string& guid,
    const FSensorExternalSwitchInput& ext_sw_inp) = 0;
  virtual ErrorOr<FSensorADCInput> GetADCInput(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetADCInput(
    const std::string& guid,
    const FSensorADCInput& adc_inp) = 0;
  virtual ErrorOr<FCallibriStimulatorMAState> GetStimulatorMAState(const std::string& guid) = 0;
  virtual ErrorOr<FCallibriStimulationParams> GetStimulatorParam(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetStimulatorParam(
    const std::string& guid,
    const FCallibriStimulationParams& param) = 0;
  virtual ErrorOr<FCallibriMotionAssistantParams> GetMotionAssistantParam(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetMotionAssistantParam(
    const std::string& guid,
    const FCallibriMotionAssistantParams& param) = 0;
  virtual ErrorOr<FCallibriMotionCounterParam> GetMotionCounterParam(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetMotionCounterParam(
    const std::string& guid,
    const FCallibriMotionCounterParam& param) = 0;
  virtual ErrorOr<int64_t> GetMotionCounter(const std::string& guid) = 0;
  virtual ErrorOr<FCallibriColorType> GetColor(const std::string& guid) = 0;
  virtual ErrorOr<bool> GetMEMSCalibrateState(const std::string& guid) = 0;
  virtual ErrorOr<FSensorSamplingFrequency> GetSamplingFrequencyResp(const std::string& guid) = 0;
  virtual ErrorOr<FSensorSamplingFrequency> GetSamplingFrequencyEnvelope(const std::string& guid) = 0;
  virtual ErrorOr<CallibriSignalType> GetSignalType(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetSignalType(
    const std::string& guid,
    const CallibriSignalType& type) = 0;
  virtual ErrorOr<FCallibriElectrodeState> GetElectrodeState(const std::string& guid) = 0;
  virtual ErrorOr<FSensorAccelerometerSensitivity> GetAccSens(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetAccSens(
    const std::string& guid,
    const FSensorAccelerometerSensitivity& acc_sens) = 0;
  virtual ErrorOr<FSensorGyroscopeSensitivity> GetGyroSens(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetGyroSens(
    const std::string& guid,
    const FSensorGyroscopeSensitivity& gyro_sens) = 0;
  virtual ErrorOr<FSensorSamplingFrequency> GetSamplingFrequencyMEMS(const std::string& guid) = 0;
  virtual ErrorOr<flutter::EncodableList> GetSupportedChannels(const std::string& guid) = 0;
  virtual ErrorOr<BrainBit2AmplifierParamNative> GetAmplifierParamBB2(const std::string& guid) = 0;
  virtual std::optional<FlutterError> SetAmplifierParamBB2(
    const std::string& guid,
    const BrainBit2AmplifierParamNative& param) = 0;

  // The codec used by NeuroApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `NeuroApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    NeuroApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    NeuroApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  NeuroApi() = default;
};
}  // namespace pigeon_neuro_api
#endif  // PIGEON_PIGEON_MESSAGES_G_H_
